<?php 
declare(strict_types=1);
//app config file

return [
    'app' => [
        'name' => 'TinyCat',
        'version' => '1.0.0',
        'debug' => true,
        'locale' => 'en',
    ],
    'database' => [
        'driver' => 'mysql',
        'host' => 'localhost',
        'name' => 'micro',
        'user' => 'root',
        'password' => '',
        'charset' => 'utf8mb4',
    ],
    'i18n' => [
        'locale' => 'en',
        'fallback' => 'en',
        'directory' => __DIR__ . '/lang',
    ],
    'datetime' => [
        'timezone' => 'Europe/Prague',
        'date' => 'd.m.Y',
        'time' => 'H:i',
        'datetime' => 'd.m.Y H:i',
        'database' => 'Y-m-d H:i:s',
        'iso' => DATE_ATOM,
    ],
    'auth' => [
        'table' => 'users',
        'id' => 'id',
        'login' => 'email',
        'password' => 'password',
        'name' => 'name',
        'role' => 'role',
        'status' => 'status',
        'active' => 'active',
        'session' => 'auth_user_id',
        'login_url' => '/login',
        'home_url' => '/admin/users',
        'seed' => [
            'enabled' => true,
            'login' => 'admin@example.test',
            'password' => 'tinycat123',
        ],
    ],
    'assets' => [
        'url' => '/assets',
        'directory' => __DIR__ . '/assets',
        'icons' => 'icons.svg',
        'version' => true,
    ],
    'upload' => [
        'directory' => __DIR__ . DIRECTORY_SEPARATOR . 'storage' . DIRECTORY_SEPARATOR . 'uploads',
        'url' => '/uploads',
        'subfolder' => 'Y/m',
        'max_size' => 5 * 1024 * 1024,
        'extensions' => ['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'pdf', 'txt', 'csv', 'doc', 'docx', 'xls', 'xlsx', 'zip'],
        'mime_types' => [
            'image/jpeg',
            'image/png',
            'image/gif',
            'image/webp',
            'image/svg+xml',
            'application/pdf',
            'text/plain',
            'text/csv',
            'application/msword',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'application/vnd.ms-excel',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'application/zip',
        ],
        'overwrite' => false,
        'profiles' => [
            'image' => [
                'max_size' => 3 * 1024 * 1024,
                'extensions' => ['jpg', 'jpeg', 'png', 'gif', 'webp'],
                'mime_types' => ['image/jpeg', 'image/png', 'image/gif', 'image/webp'],
            ],
            'avatar' => [
                'directory' => __DIR__ . DIRECTORY_SEPARATOR . 'storage' . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'avatars',
                'url' => '/uploads/avatars',
                'max_size' => 1 * 1024 * 1024,
                'extensions' => ['jpg', 'jpeg', 'png', 'webp'],
                'mime_types' => ['image/jpeg', 'image/png', 'image/webp'],
            ],
            'document' => [
                'max_size' => 10 * 1024 * 1024,
                'extensions' => ['pdf', 'txt', 'csv', 'doc', 'docx', 'xls', 'xlsx'],
                'mime_types' => [
                    'application/pdf',
                    'text/plain',
                    'text/csv',
                    'application/msword',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                    'application/vnd.ms-excel',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                ],
            ],
        ],
    ],
    'directory' => [
        'base' => __DIR__,
        'app' => __DIR__ . '/App',
        'public' => __DIR__ . '/Public',
        'lang' => __DIR__ . '/lang',
        'assets' => __DIR__ . '/assets',
        'uploads' => __DIR__ . DIRECTORY_SEPARATOR . 'storage' . DIRECTORY_SEPARATOR . 'uploads',
        'editor' => __DIR__ . '/assets/editor',
        'css' => __DIR__ . '/assets/css',
        'js' => __DIR__ . '/assets/js',
    ],
];
